Add middle testJar task which essentially constructs the test JARs for both SpringCoat and SummerCoat so testing is done quicker.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -93,6 +93,28 @@ jobs:
           path: ~/test-results
       - store_artifacts:
           path: ~/test-results/junit
+  constuct_testjars:
+    executor: buildenv
+    steps:
+      - checkout
+      - attach_workspace:
+          at: .
+      - run:
+          name: Constuct Test JARs
+          command: ./gradlew testJar --continue --parallel
+      - persist_to_workspace:
+          root: .
+          paths:
+            - '.gradle/*'
+            - 'build/*'
+            - 'buildSrc/.gradle/*'
+            - 'buildSrc/build/*'
+            - 'emulators/build/*'
+            - 'emulators/*/build/*'
+            - 'modules/build/*'
+            - 'modules/*/build/*'
+            - 'tools/build/*'
+            - 'tools/*/build/*'
   test_springcoat:
     executor: buildenv
     steps:
@@ -125,6 +147,38 @@ jobs:
           path: ~/test-results/junit
       - store_artifacts:
           path: ~/test-results/nps
+  test_summercoat:
+    executor: buildenv
+    steps:
+      - checkout
+      - attach_workspace:
+          at: .
+      - run:
+          name: SummerCoat Tests
+          command: |
+            if ! ./gradlew testSummerCoat --continue --parallel
+            then
+              echo "SummerCoat testing failed, ignoring..." 1>&2
+            fi
+          no_output_timeout: 2m
+      - run:
+          name: Save test results
+          command: |
+            mkdir -p ~/test-results/junit/
+            find . -type f -regex '.*/summercoat/junit-reports/.*xml' -exec cp {} ~/test-results/junit/ \;
+          when: always
+      - run:
+          name: Save snapshots
+          command: |
+            mkdir -p ~/test-results/nps/
+            find . -type f -regex '.*/summercoat/nps/.*nps' -exec cp {} ~/test-results/nps/ \;
+          when: always
+      - store_test_results:
+          path: ~/test-results
+      - store_artifacts:
+          path: ~/test-results/junit
+      - store_artifacts:
+          path: ~/test-results/nps
 
 workflows:
   version: 2
@@ -133,8 +187,12 @@ workflows:
       - build_windows
       - build_linux
       - build_macosx
+      - constuct_testjars:
+          requires:
+            - build_linux
       - test_springcoat:
           requires:
-            - build_windows
-            - build_linux
-            - build_macosx
+            - constuct_testjars
+      - test_summercoat:
+          requires:
+            - constuct_testjars
