Better way to ignore failures.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -86,7 +86,11 @@ jobs:
       - checkout
       - run:
           name: SpringCoat Tests
-          command: ./gradlew testSpringCoat --continue --parallel
+          command: |
+            if ! ./gradlew testSpringCoat --continue --parallel
+            then
+              echo "SpringCoat testing failed, ignoring..." 1>&2
+            fi
           no_output_timeout: 2m
       - run:
           name: Save test results
@@ -106,10 +110,6 @@ jobs:
           path: ~/test-results/junit
       - store_artifacts:
           path: ~/test-results/nps
-      - run:
-          name: Halting due to test failures
-          command: circleci step halt
-          when: on_fail
 
 workflows:
   version: 2
